### ISSUE TITLE
Meldung im Log nach Start

### ISSUE THREAD

**Issue by mymeyer** [liv-in-sky/sonoff-iobroker-script#1]
Hi, folgende Meldungen bekomme ich im Log wenn ich das Script startet:

`

javascript.0 | 2021-12-14 22:10:43.798 | info | script.js.Allgemein.SonOff_Geräte: registered 0 subscriptions and 0 schedules
-- | -- | -- | --
javascript.0 | 2021-12-14 22:10:43.797 | warn | at script.js.Allgemein.SonOff_Geräte:1257:3
javascript.0 | 2021-12-14 22:10:43.797 | warn | at script.js.Allgemein.SonOff_Geräte:667:5
javascript.0 | 2021-12-14 22:10:43.797 | warn | at writeHTML (script.js.Allgemein.SonOff_Geräte:511:121)
javascript.0 | 2021-12-14 22:10:43.796 | warn | getState "sonoff.0.LUX-Wert.POWER" not found (3) states[id]=null
javascript.0 | 2021-12-14 22:10:43.796 | warn | at script.js.Allgemein.SonOff_Geräte:1257:3
javascript.0 | 2021-12-14 22:10:43.796 | warn | at script.js.Allgemein.SonOff_Geräte:667:5
javascript.0 | 2021-12-14 22:10:43.796 | warn | at writeHTML (script.js.Allgemein.SonOff_Geräte:511:121)
javascript.0 | 2021-12-14 22:10:43.796 | warn | getState "sonoff.0.Drucksensor.POWER" not found (3) states[id]=null
javascript.0 | 2021-12-14 22:10:43.796 | warn | at script.js.Allgemein.SonOff_Geräte:1257:3
javascript.0 | 2021-12-14 22:10:43.795 | warn | at script.js.Allgemein.SonOff_Geräte:667:5
javascript.0 | 2021-12-14 22:10:43.795 | warn | at writeHTML (script.js.Allgemein.SonOff_Geräte:511:121)
javascript.0 | 2021-12-14 22:10:43.795 | warn | getState "sonoff.0.CO2-Wohnbereich.POWER" not found (3) states[id]=null
javascript.0 | 2021-12-14 22:10:43.795 | warn | at script.js.Allgemein.SonOff_Geräte:1257:3
javascript.0 | 2021-12-14 22:10:43.795 | warn | at script.js.Allgemein.SonOff_Geräte:667:5
javascript.0 | 2021-12-14 22:10:43.794 | warn | at writeHTML (script.js.Allgemein.SonOff_Geräte:511:121)
javascript.0 | 2021-12-14 22:10:43.791 | warn | getState "sonoff.0.CO2-Schlafbereich.POWER" not found (3) states[id]=null
javascript.0 | 2021-12-14 22:10:43.718 | info | Start javascript script.js.Allgemein.SonOff_Geräte

`
MM

**Comment by liv-in-sky** [comment]
@mymeyer 

bin mir nicht ganz sicher
klicke mal in alle states (im admin bei object-tab) , die im log angegeben werden - so dass dort false oder true drinsteht - anscheinend fehlt eine if exists abfrage

**Comment by mymeyer** [comment]
hi, ja das war es, weil bei den Geräten handelt es sich um Messgeräte die haben keine Power True/False. Das Feld Power war leer. Deswegen die Fehler im Log. Jetzt läuft es gut.
