### ISSUE TITLE
Tasmota 10.1 werden nicht angezeigt 

### ISSUE THREAD

**Issue by mymeyer** [liv-in-sky/sonoff-iobroker-script#2]
HAllo, bei mir werden die Tasmota 10.x Geräte nicht angezeigt.

Hier die Datenpunkte unter Info:
![image](https://user-images.githubusercontent.com/44463914/149207941-c25eaf0e-c021-401f-ba22-c941e44bd14d.png)

Michael

**Comment by liv-in-sky** [comment]
@mymeyer 
ich habe nur einen - der wird auch angezeigt
hast du das neuste script? hast du im log einen fehler? 
könntest du im forum im thread antworten ? https://forum.iobroker.net/post/733896

**Comment by mymeyer** [comment]
hi.. anscheinend habe ich den bereits bei mir gefunden. :-) Danke Dir.
