### ISSUE TITLE
abbruch spalte0 ncht da

### ISSUE THREAD

**Issue by arteck** [liv-in-sky/sonoff-iobroker-script#3]
![grafik](https://user-images.githubusercontent.com/6681528/153404277-7b3f1318-672a-4de0-bb44-fa59ab153a78.png)
![grafik](https://user-images.githubusercontent.com/6681528/153404588-ac411eb9-afc3-4a9f-bbfc-34911b6c1c3e.png)

**Comment by liv-in-sky** [comment]
spalte 0 ist eigentlich der hostname - hat einer deiner sonoffs keinen hostnamen oder den dp hostnamen nicht ?

**Comment by liv-in-sky** [comment]
oder hast du die spalte 0 ausgeblendet ?

**Comment by liv-in-sky** [comment]
zeig mal die zeilen des settings 68 - 80

**Comment by arteck** [comment]
ja alle meine sonoffs haben einen namen
und nö sollte da sein
![grafik](https://user-images.githubusercontent.com/6681528/153407843-69e3d6c1-1784-46a0-b231-0ba9d64b7d93.png)

**Comment by arteck** [comment]
der legt mir spalten an wo keine mehr sein sollten
![grafik](https://user-images.githubusercontent.com/6681528/153408079-0160896e-5f12-48c5-86fa-30f87e47118a.png)

**Comment by liv-in-sky** [comment]
hast du die dp mal alle gelöscht und das script neu gestartet

**Comment by arteck** [comment]
jo

**Comment by liv-in-sky** [comment]
schaut bei mir so aus
![Image 2](https://user-images.githubusercontent.com/18462890/153409440-85e3efd7-c9c1-42aa-bf78-72f6297d07c8.png)

**Comment by arteck** [comment]
ieht jetzt auch so aus nach mehreren starts
![grafik](https://user-images.githubusercontent.com/6681528/153409750-a6de05dc-23a4-41d8-9576-a1395f99a99d.png)

aber halt leer

**Comment by liv-in-sky** [comment]
zeile 20 - welche sortierung hast du

evtl. solltest du das script mal stoppen, die javascript instanz neustarten - die dp löschen und das script wieder starten

die fehlermeldung verweist auf eine zeile, die nicht da ist - das ist seltsam

**Comment by liv-in-sky** [comment]
hier mal das script , das bei mir läuft- nicht das da was falsch läuft
[sonoff-neu.txt](https://github.com/liv-in-sky/sonoff-iobroker-script/files/8040990/sonoff-neu.txt)

**Comment by arteck** [comment]
let welcheSortierung=1;  
jetzt hab och da was drin..

**Comment by liv-in-sky** [comment]
was heiß das ? es läuft ?

**Comment by arteck** [comment]
![grafik](https://user-images.githubusercontent.com/6681528/153411378-f789d1c9-b33e-4422-ac78-1085a3af093c.png)
ja aber der name stimmt nicht

**Comment by arteck** [comment]
![grafik](https://user-images.githubusercontent.com/6681528/153411584-39e2048e-1139-44e1-aa24-12e77c37bb44.png)

**Comment by arteck** [comment]
augen auf...ich habs

**Comment by arteck** [comment]
läuft..komisch nur das der nicht direkt die objekte angelegt hat..

**Comment by liv-in-sky** [comment]
wenn es läuft - sag bescheid

mich würde noch interessieren, was du für einstellungen hast - nutzt du die treeview?
hast du geräte >= version 9.5

**Comment by liv-in-sky** [comment]
und gleichzeitig kleiner version  9.5

**Comment by arteck** [comment]
![grafik](https://user-images.githubusercontent.com/6681528/153415827-2cf61acb-d019-4e9e-b2c2-d540de1972ea.png)

**Comment by arteck** [comment]
da

**Comment by arteck** [comment]
hier ist noch ne verschiebung
![grafik](https://user-images.githubusercontent.com/6681528/153415911-0a694bcb-1e33-4787-92d6-ecf1db523365.png)

**Comment by liv-in-sky** [comment]
zeig mal alle dp von Bildheizung

**Comment by liv-in-sky** [comment]
mach mal das auf true   let showInstanzInName=true;  zeile 26

und zeig die tabelle nochmal

**Comment by liv-in-sky** [comment]
hast du aufgegeben? das sieht eigentlich danach aus, als ob die selben geräte in unterschiedlichen instanzen sind - und beim sammeln der daten oder sortieren etwas schief geht

du kannst auch mal testen, indem du beim selektor nur eine instanz wählst
